name: Master - Push

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint and Test
      run: |
        npm install -g firebase-tools
        firebase use wearequarantined
        cd api && firebase deploy --only functions --token "$FIREBASE_TOKEN"
      env:
        CI: true
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
