name: Master - Push

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy to Firebase
      run: |
        npm install -g firebase-tools
        cd api && firebase use wearequarantined
        cd functions && npm i && cd ..
        firebase functions:config:set algolia.applicationId="$ALGOLIA_APPLICATION_ID" algolia.adminApiKey="$ALGOLIA_ADMIN_API_KEY"
        firebase deploy --token "$FIREBASE_TOKEN" --force
      env:
        CI: true
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
